// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xgenerateboardmatrix.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XGenerateboardmatrix_CfgInitialize(XGenerateboardmatrix *InstancePtr, XGenerateboardmatrix_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XGenerateboardmatrix_Start(XGenerateboardmatrix *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XGenerateboardmatrix_IsDone(XGenerateboardmatrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XGenerateboardmatrix_IsIdle(XGenerateboardmatrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XGenerateboardmatrix_IsReady(XGenerateboardmatrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XGenerateboardmatrix_EnableAutoRestart(XGenerateboardmatrix *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XGenerateboardmatrix_DisableAutoRestart(XGenerateboardmatrix *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XGenerateboardmatrix_Set_boardOffset(XGenerateboardmatrix *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_BOARDOFFSET_DATA, Data);
}

u32 XGenerateboardmatrix_Get_boardOffset(XGenerateboardmatrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_BOARDOFFSET_DATA);
    return Data;
}

void XGenerateboardmatrix_Set_pieceChar(XGenerateboardmatrix *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_PIECECHAR_DATA, Data);
}

u32 XGenerateboardmatrix_Get_pieceChar(XGenerateboardmatrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_PIECECHAR_DATA);
    return Data;
}

void XGenerateboardmatrix_Set_boardArrayOffset(XGenerateboardmatrix *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_BOARDARRAYOFFSET_DATA, Data);
}

u32 XGenerateboardmatrix_Get_boardArrayOffset(XGenerateboardmatrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_BOARDARRAYOFFSET_DATA);
    return Data;
}

void XGenerateboardmatrix_Set_landingHeightArrayOffset(XGenerateboardmatrix *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_LANDINGHEIGHTARRAYOFFSET_DATA, Data);
}

u32 XGenerateboardmatrix_Get_landingHeightArrayOffset(XGenerateboardmatrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_LANDINGHEIGHTARRAYOFFSET_DATA);
    return Data;
}

void XGenerateboardmatrix_Set_placementValidOffset(XGenerateboardmatrix *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_PLACEMENTVALIDOFFSET_DATA, Data);
}

u32 XGenerateboardmatrix_Get_placementValidOffset(XGenerateboardmatrix *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_PLACEMENTVALIDOFFSET_DATA);
    return Data;
}

void XGenerateboardmatrix_InterruptGlobalEnable(XGenerateboardmatrix *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_GIE, 1);
}

void XGenerateboardmatrix_InterruptGlobalDisable(XGenerateboardmatrix *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_GIE, 0);
}

void XGenerateboardmatrix_InterruptEnable(XGenerateboardmatrix *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_IER);
    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XGenerateboardmatrix_InterruptDisable(XGenerateboardmatrix *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_IER);
    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XGenerateboardmatrix_InterruptClear(XGenerateboardmatrix *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGenerateboardmatrix_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XGenerateboardmatrix_InterruptGetEnabled(XGenerateboardmatrix *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_IER);
}

u32 XGenerateboardmatrix_InterruptGetStatus(XGenerateboardmatrix *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGenerateboardmatrix_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XGENERATEBOARDMATRIX_CTRL_BUS_ADDR_ISR);
}

