##Switches
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[0]}]
#IO_L24N_T3_RS0_15 Sch=sw[0]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[1]}]
#IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[2]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[3]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[4]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[5]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[6]}]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[7]}]
set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS18} [get_ports {gpio_io_i[8]}]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS18} [get_ports {gpio_io_i[9]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[10]}]
set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[11]}]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[12]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[13]}]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[14]}]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {gpio_io_i[15]}]

## LEDs
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[0]}]
#IO_L18P_T2_A24_15 Sch=led[0]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[1]}]
#IO_L24P_T3_RS1_15 Sch=led[1]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[2]}]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[3]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[4]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[5]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[6]}]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[7]}]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[8]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[9]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[10]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[11]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[12]}]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[13]}]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[14]}]
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o[15]}]

set_property PACKAGE_PIN A3 [get_ports {tft_vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_r[0]}]
set_property PACKAGE_PIN B4 [get_ports {tft_vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_r[1]}]
set_property PACKAGE_PIN C5 [get_ports {tft_vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_r[2]}]
set_property PACKAGE_PIN A4 [get_ports {tft_vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_r[3]}]

set_property PACKAGE_PIN C6 [get_ports {tft_vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_g[0]}]
set_property PACKAGE_PIN A5 [get_ports {tft_vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_g[1]}]
set_property PACKAGE_PIN B6 [get_ports {tft_vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_g[2]}]
set_property PACKAGE_PIN A6 [get_ports {tft_vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_g[3]}]

set_property PACKAGE_PIN B7 [get_ports {tft_vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_b[0]}]
set_property PACKAGE_PIN C7 [get_ports {tft_vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_b[1]}]
set_property PACKAGE_PIN D7 [get_ports {tft_vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_b[2]}]
set_property PACKAGE_PIN D8 [get_ports {tft_vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tft_vga_b[3]}]

set_property PACKAGE_PIN B11 [get_ports tft_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports tft_hsync]
set_property PACKAGE_PIN B12 [get_ports tft_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports tft_vsync]


set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
