// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xeltetris2.h"

extern XEltetris2_Config XEltetris2_ConfigTable[];

XEltetris2_Config *XEltetris2_LookupConfig(u16 DeviceId) {
	XEltetris2_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XELTETRIS2_NUM_INSTANCES; Index++) {
		if (XEltetris2_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEltetris2_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEltetris2_Initialize(XEltetris2 *InstancePtr, u16 DeviceId) {
	XEltetris2_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEltetris2_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEltetris2_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

