// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XGENERATEBOARDMATRIX_H
#define XGENERATEBOARDMATRIX_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xgenerateboardmatrix_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XGenerateboardmatrix_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XGenerateboardmatrix;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XGenerateboardmatrix_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XGenerateboardmatrix_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XGenerateboardmatrix_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XGenerateboardmatrix_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XGenerateboardmatrix_Initialize(XGenerateboardmatrix *InstancePtr, u16 DeviceId);
XGenerateboardmatrix_Config* XGenerateboardmatrix_LookupConfig(u16 DeviceId);
int XGenerateboardmatrix_CfgInitialize(XGenerateboardmatrix *InstancePtr, XGenerateboardmatrix_Config *ConfigPtr);
#else
int XGenerateboardmatrix_Initialize(XGenerateboardmatrix *InstancePtr, const char* InstanceName);
int XGenerateboardmatrix_Release(XGenerateboardmatrix *InstancePtr);
#endif

void XGenerateboardmatrix_Start(XGenerateboardmatrix *InstancePtr);
u32 XGenerateboardmatrix_IsDone(XGenerateboardmatrix *InstancePtr);
u32 XGenerateboardmatrix_IsIdle(XGenerateboardmatrix *InstancePtr);
u32 XGenerateboardmatrix_IsReady(XGenerateboardmatrix *InstancePtr);
void XGenerateboardmatrix_EnableAutoRestart(XGenerateboardmatrix *InstancePtr);
void XGenerateboardmatrix_DisableAutoRestart(XGenerateboardmatrix *InstancePtr);

void XGenerateboardmatrix_Set_boardOffset(XGenerateboardmatrix *InstancePtr, u32 Data);
u32 XGenerateboardmatrix_Get_boardOffset(XGenerateboardmatrix *InstancePtr);
void XGenerateboardmatrix_Set_pieceChar(XGenerateboardmatrix *InstancePtr, u32 Data);
u32 XGenerateboardmatrix_Get_pieceChar(XGenerateboardmatrix *InstancePtr);
void XGenerateboardmatrix_Set_boardArrayOffset(XGenerateboardmatrix *InstancePtr, u32 Data);
u32 XGenerateboardmatrix_Get_boardArrayOffset(XGenerateboardmatrix *InstancePtr);
void XGenerateboardmatrix_Set_landingHeightArrayOffset(XGenerateboardmatrix *InstancePtr, u32 Data);
u32 XGenerateboardmatrix_Get_landingHeightArrayOffset(XGenerateboardmatrix *InstancePtr);
void XGenerateboardmatrix_Set_placementValidOffset(XGenerateboardmatrix *InstancePtr, u32 Data);
u32 XGenerateboardmatrix_Get_placementValidOffset(XGenerateboardmatrix *InstancePtr);

void XGenerateboardmatrix_InterruptGlobalEnable(XGenerateboardmatrix *InstancePtr);
void XGenerateboardmatrix_InterruptGlobalDisable(XGenerateboardmatrix *InstancePtr);
void XGenerateboardmatrix_InterruptEnable(XGenerateboardmatrix *InstancePtr, u32 Mask);
void XGenerateboardmatrix_InterruptDisable(XGenerateboardmatrix *InstancePtr, u32 Mask);
void XGenerateboardmatrix_InterruptClear(XGenerateboardmatrix *InstancePtr, u32 Mask);
u32 XGenerateboardmatrix_InterruptGetEnabled(XGenerateboardmatrix *InstancePtr);
u32 XGenerateboardmatrix_InterruptGetStatus(XGenerateboardmatrix *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
