// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XELTETRIS2_H
#define XELTETRIS2_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xeltetris2_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XEltetris2_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XEltetris2;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XEltetris2_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XEltetris2_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XEltetris2_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XEltetris2_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XEltetris2_Initialize(XEltetris2 *InstancePtr, u16 DeviceId);
XEltetris2_Config* XEltetris2_LookupConfig(u16 DeviceId);
int XEltetris2_CfgInitialize(XEltetris2 *InstancePtr, XEltetris2_Config *ConfigPtr);
#else
int XEltetris2_Initialize(XEltetris2 *InstancePtr, const char* InstanceName);
int XEltetris2_Release(XEltetris2 *InstancePtr);
#endif

void XEltetris2_Start(XEltetris2 *InstancePtr);
u32 XEltetris2_IsDone(XEltetris2 *InstancePtr);
u32 XEltetris2_IsIdle(XEltetris2 *InstancePtr);
u32 XEltetris2_IsReady(XEltetris2 *InstancePtr);
void XEltetris2_EnableAutoRestart(XEltetris2 *InstancePtr);
void XEltetris2_DisableAutoRestart(XEltetris2 *InstancePtr);

void XEltetris2_Set_board_offset(XEltetris2 *InstancePtr, u32 Data);
u32 XEltetris2_Get_board_offset(XEltetris2 *InstancePtr);
void XEltetris2_Set_landingHeight_offset(XEltetris2 *InstancePtr, u32 Data);
u32 XEltetris2_Get_landingHeight_offset(XEltetris2 *InstancePtr);
void XEltetris2_Set_num_batches(XEltetris2 *InstancePtr, u32 Data);
u32 XEltetris2_Get_num_batches(XEltetris2 *InstancePtr);
void XEltetris2_Set_scoreArrayOffset(XEltetris2 *InstancePtr, u32 Data);
u32 XEltetris2_Get_scoreArrayOffset(XEltetris2 *InstancePtr);

void XEltetris2_InterruptGlobalEnable(XEltetris2 *InstancePtr);
void XEltetris2_InterruptGlobalDisable(XEltetris2 *InstancePtr);
void XEltetris2_InterruptEnable(XEltetris2 *InstancePtr, u32 Mask);
void XEltetris2_InterruptDisable(XEltetris2 *InstancePtr, u32 Mask);
void XEltetris2_InterruptClear(XEltetris2 *InstancePtr, u32 Mask);
u32 XEltetris2_InterruptGetEnabled(XEltetris2 *InstancePtr);
u32 XEltetris2_InterruptGetStatus(XEltetris2 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
