// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __generateBoardMatrbkb_H__
#define __generateBoardMatrbkb_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct generateBoardMatrbkb_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 4;
  static const unsigned AddressRange = 28;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(generateBoardMatrbkb_ram) {
        ram[0] = "0b1010";
        ram[1] = "0b0110";
        ram[2] = "0b1010";
        ram[3] = "0b0110";
        ram[4] = "0b1000";
        ram[5] = "0b0111";
        ram[6] = "0b1000";
        ram[7] = "0b0111";
        ram[8] = "0b1000";
        ram[9] = "0b0111";
        ram[10] = "0b1000";
        ram[11] = "0b0111";
        ram[12] = "0b1000";
        ram[13] = "0b0111";
        ram[14] = "0b1000";
        ram[15] = "0b0111";
        ram[16] = "0b1000";
        ram[17] = "0b0111";
        ram[18] = "0b1000";
        ram[19] = "0b0111";
        for (unsigned i = 20; i < 25 ; i = i + 1) {
            ram[i] = "0b1000";
        }
        ram[25] = "0b0111";
        ram[26] = "0b1000";
        ram[27] = "0b0111";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(generateBoardMatrbkb) {


static const unsigned DataWidth = 4;
static const unsigned AddressRange = 28;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


generateBoardMatrbkb_ram* meminst;


SC_CTOR(generateBoardMatrbkb) {
meminst = new generateBoardMatrbkb_ram("generateBoardMatrbkb_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~generateBoardMatrbkb() {
    delete meminst;
}


};//endmodule
#endif
