// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "getRowScores.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic getRowScores::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic getRowScores::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<54> getRowScores::ap_ST_fsm_state1 = "1";
const sc_lv<54> getRowScores::ap_ST_fsm_state2 = "10";
const sc_lv<54> getRowScores::ap_ST_fsm_state3 = "100";
const sc_lv<54> getRowScores::ap_ST_fsm_state4 = "1000";
const sc_lv<54> getRowScores::ap_ST_fsm_state5 = "10000";
const sc_lv<54> getRowScores::ap_ST_fsm_state6 = "100000";
const sc_lv<54> getRowScores::ap_ST_fsm_state7 = "1000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state8 = "10000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state9 = "100000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state10 = "1000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state11 = "10000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state12 = "100000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<54> getRowScores::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<32> getRowScores::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> getRowScores::ap_const_lv32_F = "1111";
const sc_lv<32> getRowScores::ap_const_lv32_2E = "101110";
const sc_lv<32> getRowScores::ap_const_lv32_1 = "1";
const sc_lv<1> getRowScores::ap_const_lv1_0 = "0";
const sc_lv<32> getRowScores::ap_const_lv32_2 = "10";
const sc_lv<32> getRowScores::ap_const_lv32_3 = "11";
const sc_lv<32> getRowScores::ap_const_lv32_4 = "100";
const sc_lv<32> getRowScores::ap_const_lv32_5 = "101";
const sc_lv<32> getRowScores::ap_const_lv32_9 = "1001";
const sc_lv<32> getRowScores::ap_const_lv32_A = "1010";
const sc_lv<32> getRowScores::ap_const_lv32_34 = "110100";
const sc_lv<5> getRowScores::ap_const_lv5_0 = "00000";
const sc_lv<8> getRowScores::ap_const_lv8_0 = "00000000";
const sc_lv<32> getRowScores::ap_const_lv32_35 = "110101";
const sc_lv<32> getRowScores::ap_const_lv32_2F = "101111";
const sc_lv<64> getRowScores::ap_const_lv64_400B8148A1086447 = "100000000001011100000010100100010100001000010000110010001000111";
const sc_lv<64> getRowScores::ap_const_lv64_C009BE3C36D1935E = "1100000000001001101111100011110000110110110100011001001101011110";
const sc_lv<32> getRowScores::ap_const_lv32_29 = "101001";
const sc_lv<64> getRowScores::ap_const_lv64_4024000000000000 = "100000000100100000000000000000000000000000000000000000000000000";
const sc_lv<32> getRowScores::ap_const_lv32_10 = "10000";
const sc_lv<4> getRowScores::ap_const_lv4_0 = "0000";
const sc_lv<2> getRowScores::ap_const_lv2_0 = "00";
const sc_lv<5> getRowScores::ap_const_lv5_14 = "10100";
const sc_lv<5> getRowScores::ap_const_lv5_1 = "1";
const sc_lv<1> getRowScores::ap_const_lv1_1 = "1";
const bool getRowScores::ap_const_boolean_1 = true;

getRowScores::getRowScores(sc_module_name name) : sc_module(name), mVcdFile(0) {
    elTetris2_fptruncbkb_U0 = new elTetris2_fptruncbkb<1,1,64,32>("elTetris2_fptruncbkb_U0");
    elTetris2_fptruncbkb_U0->din0(tmp_5_reg_797);
    elTetris2_fptruncbkb_U0->dout(score_fu_259_p1);
    elTetris2_dadd_64cud_U1 = new elTetris2_dadd_64cud<1,6,64,64,64>("elTetris2_dadd_64cud_U1");
    elTetris2_dadd_64cud_U1->clk(ap_clk);
    elTetris2_dadd_64cud_U1->reset(ap_rst);
    elTetris2_dadd_64cud_U1->din0(reg_280);
    elTetris2_dadd_64cud_U1->din1(tmp_4_reg_792);
    elTetris2_dadd_64cud_U1->ce(ap_var_for_const0);
    elTetris2_dadd_64cud_U1->dout(grp_fu_262_p2);
    elTetris2_dmul_64dEe_U2 = new elTetris2_dmul_64dEe<1,6,64,64,64>("elTetris2_dmul_64dEe_U2");
    elTetris2_dmul_64dEe_U2->clk(ap_clk);
    elTetris2_dmul_64dEe_U2->reset(ap_rst);
    elTetris2_dmul_64dEe_U2->din0(grp_fu_266_p0);
    elTetris2_dmul_64dEe_U2->din1(grp_fu_266_p1);
    elTetris2_dmul_64dEe_U2->ce(ap_var_for_const0);
    elTetris2_dmul_64dEe_U2->dout(grp_fu_266_p2);
    elTetris2_ddiv_64eOg_U3 = new elTetris2_ddiv_64eOg<1,31,64,64,64>("elTetris2_ddiv_64eOg_U3");
    elTetris2_ddiv_64eOg_U3->clk(ap_clk);
    elTetris2_ddiv_64eOg_U3->reset(ap_rst);
    elTetris2_ddiv_64eOg_U3->din0(reg_280);
    elTetris2_ddiv_64eOg_U3->din1(ap_var_for_const1);
    elTetris2_ddiv_64eOg_U3->ce(ap_var_for_const0);
    elTetris2_ddiv_64eOg_U3->dout(grp_fu_272_p2);
    elTetris2_sitodp_fYi_U4 = new elTetris2_sitodp_fYi<1,6,32,64>("elTetris2_sitodp_fYi_U4");
    elTetris2_sitodp_fYi_U4->clk(ap_clk);
    elTetris2_sitodp_fYi_U4->reset(ap_rst);
    elTetris2_sitodp_fYi_U4->din0(grp_fu_277_p0);
    elTetris2_sitodp_fYi_U4->ce(ap_var_for_const0);
    elTetris2_sitodp_fYi_U4->dout(grp_fu_277_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state47);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state48);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state53);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state54);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state54 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state54 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state54 );
    sensitive << ( score_fu_259_p1 );

    SC_METHOD(thread_board_0_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_0_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_board_1_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_1_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_board_2_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_2_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_board_3_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_3_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_board_4_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_4_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_board_5_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_5_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_board_6_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_6_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_board_7_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_7_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_board_8_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_8_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_board_9_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_14_cast_fu_367_p1 );

    SC_METHOD(thread_board_9_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_elimCounter_2_s_fu_644_p2);
    sensitive << ( elimCounter_reg_235 );
    sensitive << ( p_cast_fu_640_p1 );

    SC_METHOD(thread_elimCounter_cast_fu_650_p1);
    sensitive << ( elimCounter_reg_235 );

    SC_METHOD(thread_exitcond1_fu_346_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_reg_224 );

    SC_METHOD(thread_grp_fu_266_p0);
    sensitive << ( tmp_2_reg_782 );
    sensitive << ( tmp_reg_787 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_grp_fu_266_p1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_grp_fu_277_p0);
    sensitive << ( elimCounter_cast_fu_650_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( rowTranCounter_cast_fu_655_p1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_p_cast1_fu_581_p1);
    sensitive << ( tmp_7_fu_575_p2 );

    SC_METHOD(thread_p_cast_fu_640_p1);
    sensitive << ( tmp_16_fu_634_p2 );

    SC_METHOD(thread_p_shl1_cast_fu_336_p1);
    sensitive << ( tmp_12_fu_328_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_294_p1);
    sensitive << ( tmp_8_fu_286_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_306_p1);
    sensitive << ( tmp_9_fu_298_p3 );

    SC_METHOD(thread_p_shl_cast_fu_324_p1);
    sensitive << ( tmp_11_fu_316_p3 );

    SC_METHOD(thread_rowEliminated_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_15_cast_fu_386_p1 );

    SC_METHOD(thread_rowEliminated_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_rowTranCounter_2_s_fu_585_p2);
    sensitive << ( rowTranCounter_reg_247 );
    sensitive << ( p_cast1_fu_581_p1 );

    SC_METHOD(thread_rowTranCounter_cast_fu_655_p1);
    sensitive << ( rowTranCounter_reg_247 );

    SC_METHOD(thread_rowTran_1_cast_fu_407_p1);
    sensitive << ( tmp_6_1_fu_401_p2 );

    SC_METHOD(thread_rowTran_2_cast_fu_417_p1);
    sensitive << ( tmp_6_2_fu_411_p2 );

    SC_METHOD(thread_rowTran_3_cast_fu_427_p1);
    sensitive << ( tmp_6_3_fu_421_p2 );

    SC_METHOD(thread_rowTran_4_cast_fu_437_p1);
    sensitive << ( tmp_6_4_fu_431_p2 );

    SC_METHOD(thread_rowTran_5_cast_fu_447_p1);
    sensitive << ( tmp_6_5_fu_441_p2 );

    SC_METHOD(thread_rowTran_6_cast_fu_457_p1);
    sensitive << ( tmp_6_6_fu_451_p2 );

    SC_METHOD(thread_rowTran_7_cast_fu_467_p1);
    sensitive << ( tmp_6_7_fu_461_p2 );

    SC_METHOD(thread_rowTran_8_cast_fu_477_p1);
    sensitive << ( tmp_6_8_fu_471_p2 );

    SC_METHOD(thread_rowTran_9_cast_fu_487_p1);
    sensitive << ( tmp_6_9_fu_481_p2 );

    SC_METHOD(thread_rowTran_cast_3_fu_497_p1);
    sensitive << ( tmp_6_s_fu_491_p2 );

    SC_METHOD(thread_rowTran_cast_fu_397_p1);
    sensitive << ( tmp_s_fu_391_p2 );

    SC_METHOD(thread_row_1_fu_352_p2);
    sensitive << ( row_reg_224 );

    SC_METHOD(thread_row_cast_cast_fu_358_p1);
    sensitive << ( row_reg_224 );

    SC_METHOD(thread_tmp10_cast_fu_618_p1);
    sensitive << ( tmp10_fu_612_p2 );

    SC_METHOD(thread_tmp10_fu_612_p2);
    sensitive << ( tmp11_cast_fu_598_p1 );
    sensitive << ( tmp12_cast_fu_608_p1 );

    SC_METHOD(thread_tmp11_cast_fu_598_p1);
    sensitive << ( tmp11_fu_591_p3 );

    SC_METHOD(thread_tmp11_fu_591_p3);
    sensitive << ( rowEliminated_load_reg_733 );

    SC_METHOD(thread_tmp12_cast_fu_608_p1);
    sensitive << ( tmp12_fu_602_p3 );

    SC_METHOD(thread_tmp12_fu_602_p3);
    sensitive << ( rowEliminated_load_reg_733 );

    SC_METHOD(thread_tmp13_fu_622_p4);
    sensitive << ( rowEliminated_load_reg_733 );

    SC_METHOD(thread_tmp14_cast_fu_630_p1);
    sensitive << ( tmp13_fu_622_p4 );

    SC_METHOD(thread_tmp1_cast_fu_555_p1);
    sensitive << ( tmp1_fu_549_p2 );

    SC_METHOD(thread_tmp1_fu_549_p2);
    sensitive << ( tmp2_cast_fu_543_p1 );
    sensitive << ( tmp3_cast_fu_546_p1 );

    SC_METHOD(thread_tmp2_cast_fu_543_p1);
    sensitive << ( tmp2_reg_742 );

    SC_METHOD(thread_tmp2_fu_501_p2);
    sensitive << ( rowTran_1_cast_fu_407_p1 );
    sensitive << ( rowTran_cast_fu_397_p1 );

    SC_METHOD(thread_tmp3_cast_fu_546_p1);
    sensitive << ( tmp3_reg_747 );

    SC_METHOD(thread_tmp3_fu_513_p2);
    sensitive << ( rowTran_2_cast_fu_417_p1 );
    sensitive << ( tmp4_fu_507_p2 );

    SC_METHOD(thread_tmp4_fu_507_p2);
    sensitive << ( rowTran_4_cast_fu_437_p1 );
    sensitive << ( rowTran_3_cast_fu_427_p1 );

    SC_METHOD(thread_tmp5_cast_fu_571_p1);
    sensitive << ( tmp5_fu_565_p2 );

    SC_METHOD(thread_tmp5_fu_565_p2);
    sensitive << ( tmp6_cast_fu_559_p1 );
    sensitive << ( tmp8_cast_fu_562_p1 );

    SC_METHOD(thread_tmp6_cast_fu_559_p1);
    sensitive << ( tmp6_reg_752 );

    SC_METHOD(thread_tmp6_fu_525_p2);
    sensitive << ( rowTran_5_cast_fu_447_p1 );
    sensitive << ( tmp7_fu_519_p2 );

    SC_METHOD(thread_tmp7_fu_519_p2);
    sensitive << ( rowTran_7_cast_fu_467_p1 );
    sensitive << ( rowTran_6_cast_fu_457_p1 );

    SC_METHOD(thread_tmp8_cast_fu_562_p1);
    sensitive << ( tmp8_reg_757 );

    SC_METHOD(thread_tmp8_fu_537_p2);
    sensitive << ( rowTran_8_cast_fu_477_p1 );
    sensitive << ( tmp9_fu_531_p2 );

    SC_METHOD(thread_tmp9_fu_531_p2);
    sensitive << ( rowTran_cast_3_fu_497_p1 );
    sensitive << ( rowTran_9_cast_fu_487_p1 );

    SC_METHOD(thread_tmp_10_fu_310_p2);
    sensitive << ( p_shl3_cast_fu_306_p1 );
    sensitive << ( p_shl2_cast_fu_294_p1 );

    SC_METHOD(thread_tmp_11_fu_316_p3);
    sensitive << ( batch3 );

    SC_METHOD(thread_tmp_12_fu_328_p3);
    sensitive << ( batch3 );

    SC_METHOD(thread_tmp_13_fu_340_p2);
    sensitive << ( p_shl1_cast_fu_336_p1 );
    sensitive << ( p_shl_cast_fu_324_p1 );

    SC_METHOD(thread_tmp_14_cast_fu_367_p1);
    sensitive << ( tmp_14_fu_362_p2 );

    SC_METHOD(thread_tmp_14_fu_362_p2);
    sensitive << ( tmp_13_reg_665 );
    sensitive << ( row_cast_cast_fu_358_p1 );

    SC_METHOD(thread_tmp_15_cast_fu_386_p1);
    sensitive << ( tmp_15_fu_381_p2 );

    SC_METHOD(thread_tmp_15_fu_381_p2);
    sensitive << ( tmp_10_reg_660 );
    sensitive << ( row_cast_cast_fu_358_p1 );

    SC_METHOD(thread_tmp_16_fu_634_p2);
    sensitive << ( tmp10_cast_fu_618_p1 );
    sensitive << ( tmp14_cast_fu_630_p1 );

    SC_METHOD(thread_tmp_6_1_fu_401_p2);
    sensitive << ( board_0_q0 );
    sensitive << ( board_1_q0 );

    SC_METHOD(thread_tmp_6_2_fu_411_p2);
    sensitive << ( board_1_q0 );
    sensitive << ( board_2_q0 );

    SC_METHOD(thread_tmp_6_3_fu_421_p2);
    sensitive << ( board_2_q0 );
    sensitive << ( board_3_q0 );

    SC_METHOD(thread_tmp_6_4_fu_431_p2);
    sensitive << ( board_3_q0 );
    sensitive << ( board_4_q0 );

    SC_METHOD(thread_tmp_6_5_fu_441_p2);
    sensitive << ( board_4_q0 );
    sensitive << ( board_5_q0 );

    SC_METHOD(thread_tmp_6_6_fu_451_p2);
    sensitive << ( board_5_q0 );
    sensitive << ( board_6_q0 );

    SC_METHOD(thread_tmp_6_7_fu_461_p2);
    sensitive << ( board_6_q0 );
    sensitive << ( board_7_q0 );

    SC_METHOD(thread_tmp_6_8_fu_471_p2);
    sensitive << ( board_7_q0 );
    sensitive << ( board_8_q0 );

    SC_METHOD(thread_tmp_6_9_fu_481_p2);
    sensitive << ( board_8_q0 );
    sensitive << ( board_9_q0 );

    SC_METHOD(thread_tmp_6_s_fu_491_p2);
    sensitive << ( board_9_q0 );

    SC_METHOD(thread_tmp_7_fu_575_p2);
    sensitive << ( tmp1_cast_fu_555_p1 );
    sensitive << ( tmp5_cast_fu_571_p1 );

    SC_METHOD(thread_tmp_8_fu_286_p3);
    sensitive << ( batch31 );

    SC_METHOD(thread_tmp_9_fu_298_p3);
    sensitive << ( batch31 );

    SC_METHOD(thread_tmp_s_fu_391_p2);
    sensitive << ( board_0_q0 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_346_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "000000000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "getRowScores_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, board_0_address0, "(port)board_0_address0");
    sc_trace(mVcdFile, board_0_ce0, "(port)board_0_ce0");
    sc_trace(mVcdFile, board_0_q0, "(port)board_0_q0");
    sc_trace(mVcdFile, board_1_address0, "(port)board_1_address0");
    sc_trace(mVcdFile, board_1_ce0, "(port)board_1_ce0");
    sc_trace(mVcdFile, board_1_q0, "(port)board_1_q0");
    sc_trace(mVcdFile, board_2_address0, "(port)board_2_address0");
    sc_trace(mVcdFile, board_2_ce0, "(port)board_2_ce0");
    sc_trace(mVcdFile, board_2_q0, "(port)board_2_q0");
    sc_trace(mVcdFile, board_3_address0, "(port)board_3_address0");
    sc_trace(mVcdFile, board_3_ce0, "(port)board_3_ce0");
    sc_trace(mVcdFile, board_3_q0, "(port)board_3_q0");
    sc_trace(mVcdFile, board_4_address0, "(port)board_4_address0");
    sc_trace(mVcdFile, board_4_ce0, "(port)board_4_ce0");
    sc_trace(mVcdFile, board_4_q0, "(port)board_4_q0");
    sc_trace(mVcdFile, board_5_address0, "(port)board_5_address0");
    sc_trace(mVcdFile, board_5_ce0, "(port)board_5_ce0");
    sc_trace(mVcdFile, board_5_q0, "(port)board_5_q0");
    sc_trace(mVcdFile, board_6_address0, "(port)board_6_address0");
    sc_trace(mVcdFile, board_6_ce0, "(port)board_6_ce0");
    sc_trace(mVcdFile, board_6_q0, "(port)board_6_q0");
    sc_trace(mVcdFile, board_7_address0, "(port)board_7_address0");
    sc_trace(mVcdFile, board_7_ce0, "(port)board_7_ce0");
    sc_trace(mVcdFile, board_7_q0, "(port)board_7_q0");
    sc_trace(mVcdFile, board_8_address0, "(port)board_8_address0");
    sc_trace(mVcdFile, board_8_ce0, "(port)board_8_ce0");
    sc_trace(mVcdFile, board_8_q0, "(port)board_8_q0");
    sc_trace(mVcdFile, board_9_address0, "(port)board_9_address0");
    sc_trace(mVcdFile, board_9_ce0, "(port)board_9_ce0");
    sc_trace(mVcdFile, board_9_q0, "(port)board_9_q0");
    sc_trace(mVcdFile, batch3, "(port)batch3");
    sc_trace(mVcdFile, rowEliminated_address0, "(port)rowEliminated_address0");
    sc_trace(mVcdFile, rowEliminated_ce0, "(port)rowEliminated_ce0");
    sc_trace(mVcdFile, rowEliminated_q0, "(port)rowEliminated_q0");
    sc_trace(mVcdFile, batch31, "(port)batch31");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_266_p2, "grp_fu_266_p2");
    sc_trace(mVcdFile, reg_280, "reg_280");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state47, "ap_CS_fsm_state47");
    sc_trace(mVcdFile, tmp_10_fu_310_p2, "tmp_10_fu_310_p2");
    sc_trace(mVcdFile, tmp_10_reg_660, "tmp_10_reg_660");
    sc_trace(mVcdFile, tmp_13_fu_340_p2, "tmp_13_fu_340_p2");
    sc_trace(mVcdFile, tmp_13_reg_665, "tmp_13_reg_665");
    sc_trace(mVcdFile, row_1_fu_352_p2, "row_1_fu_352_p2");
    sc_trace(mVcdFile, row_1_reg_673, "row_1_reg_673");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond1_fu_346_p2, "exitcond1_fu_346_p2");
    sc_trace(mVcdFile, rowEliminated_load_reg_733, "rowEliminated_load_reg_733");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp2_fu_501_p2, "tmp2_fu_501_p2");
    sc_trace(mVcdFile, tmp2_reg_742, "tmp2_reg_742");
    sc_trace(mVcdFile, tmp3_fu_513_p2, "tmp3_fu_513_p2");
    sc_trace(mVcdFile, tmp3_reg_747, "tmp3_reg_747");
    sc_trace(mVcdFile, tmp6_fu_525_p2, "tmp6_fu_525_p2");
    sc_trace(mVcdFile, tmp6_reg_752, "tmp6_reg_752");
    sc_trace(mVcdFile, tmp8_fu_537_p2, "tmp8_fu_537_p2");
    sc_trace(mVcdFile, tmp8_reg_757, "tmp8_reg_757");
    sc_trace(mVcdFile, rowTranCounter_2_s_fu_585_p2, "rowTranCounter_2_s_fu_585_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, elimCounter_2_s_fu_644_p2, "elimCounter_2_s_fu_644_p2");
    sc_trace(mVcdFile, elimCounter_cast_fu_650_p1, "elimCounter_cast_fu_650_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, rowTranCounter_cast_fu_655_p1, "rowTranCounter_cast_fu_655_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_277_p1, "grp_fu_277_p1");
    sc_trace(mVcdFile, tmp_2_reg_782, "tmp_2_reg_782");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_reg_787, "tmp_reg_787");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, grp_fu_272_p2, "grp_fu_272_p2");
    sc_trace(mVcdFile, tmp_4_reg_792, "tmp_4_reg_792");
    sc_trace(mVcdFile, grp_fu_262_p2, "grp_fu_262_p2");
    sc_trace(mVcdFile, tmp_5_reg_797, "tmp_5_reg_797");
    sc_trace(mVcdFile, ap_CS_fsm_state53, "ap_CS_fsm_state53");
    sc_trace(mVcdFile, row_reg_224, "row_reg_224");
    sc_trace(mVcdFile, elimCounter_reg_235, "elimCounter_reg_235");
    sc_trace(mVcdFile, rowTranCounter_reg_247, "rowTranCounter_reg_247");
    sc_trace(mVcdFile, tmp_14_cast_fu_367_p1, "tmp_14_cast_fu_367_p1");
    sc_trace(mVcdFile, tmp_15_cast_fu_386_p1, "tmp_15_cast_fu_386_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state54, "ap_CS_fsm_state54");
    sc_trace(mVcdFile, ap_CS_fsm_state48, "ap_CS_fsm_state48");
    sc_trace(mVcdFile, grp_fu_266_p0, "grp_fu_266_p0");
    sc_trace(mVcdFile, grp_fu_266_p1, "grp_fu_266_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_277_p0, "grp_fu_277_p0");
    sc_trace(mVcdFile, tmp_8_fu_286_p3, "tmp_8_fu_286_p3");
    sc_trace(mVcdFile, tmp_9_fu_298_p3, "tmp_9_fu_298_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_306_p1, "p_shl3_cast_fu_306_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_294_p1, "p_shl2_cast_fu_294_p1");
    sc_trace(mVcdFile, tmp_11_fu_316_p3, "tmp_11_fu_316_p3");
    sc_trace(mVcdFile, tmp_12_fu_328_p3, "tmp_12_fu_328_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_336_p1, "p_shl1_cast_fu_336_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_324_p1, "p_shl_cast_fu_324_p1");
    sc_trace(mVcdFile, row_cast_cast_fu_358_p1, "row_cast_cast_fu_358_p1");
    sc_trace(mVcdFile, tmp_14_fu_362_p2, "tmp_14_fu_362_p2");
    sc_trace(mVcdFile, tmp_15_fu_381_p2, "tmp_15_fu_381_p2");
    sc_trace(mVcdFile, tmp_s_fu_391_p2, "tmp_s_fu_391_p2");
    sc_trace(mVcdFile, tmp_6_1_fu_401_p2, "tmp_6_1_fu_401_p2");
    sc_trace(mVcdFile, tmp_6_2_fu_411_p2, "tmp_6_2_fu_411_p2");
    sc_trace(mVcdFile, tmp_6_3_fu_421_p2, "tmp_6_3_fu_421_p2");
    sc_trace(mVcdFile, tmp_6_4_fu_431_p2, "tmp_6_4_fu_431_p2");
    sc_trace(mVcdFile, tmp_6_5_fu_441_p2, "tmp_6_5_fu_441_p2");
    sc_trace(mVcdFile, tmp_6_6_fu_451_p2, "tmp_6_6_fu_451_p2");
    sc_trace(mVcdFile, tmp_6_7_fu_461_p2, "tmp_6_7_fu_461_p2");
    sc_trace(mVcdFile, tmp_6_8_fu_471_p2, "tmp_6_8_fu_471_p2");
    sc_trace(mVcdFile, tmp_6_9_fu_481_p2, "tmp_6_9_fu_481_p2");
    sc_trace(mVcdFile, tmp_6_s_fu_491_p2, "tmp_6_s_fu_491_p2");
    sc_trace(mVcdFile, rowTran_1_cast_fu_407_p1, "rowTran_1_cast_fu_407_p1");
    sc_trace(mVcdFile, rowTran_cast_fu_397_p1, "rowTran_cast_fu_397_p1");
    sc_trace(mVcdFile, rowTran_4_cast_fu_437_p1, "rowTran_4_cast_fu_437_p1");
    sc_trace(mVcdFile, rowTran_3_cast_fu_427_p1, "rowTran_3_cast_fu_427_p1");
    sc_trace(mVcdFile, rowTran_2_cast_fu_417_p1, "rowTran_2_cast_fu_417_p1");
    sc_trace(mVcdFile, tmp4_fu_507_p2, "tmp4_fu_507_p2");
    sc_trace(mVcdFile, rowTran_7_cast_fu_467_p1, "rowTran_7_cast_fu_467_p1");
    sc_trace(mVcdFile, rowTran_6_cast_fu_457_p1, "rowTran_6_cast_fu_457_p1");
    sc_trace(mVcdFile, rowTran_5_cast_fu_447_p1, "rowTran_5_cast_fu_447_p1");
    sc_trace(mVcdFile, tmp7_fu_519_p2, "tmp7_fu_519_p2");
    sc_trace(mVcdFile, rowTran_cast_3_fu_497_p1, "rowTran_cast_3_fu_497_p1");
    sc_trace(mVcdFile, rowTran_9_cast_fu_487_p1, "rowTran_9_cast_fu_487_p1");
    sc_trace(mVcdFile, rowTran_8_cast_fu_477_p1, "rowTran_8_cast_fu_477_p1");
    sc_trace(mVcdFile, tmp9_fu_531_p2, "tmp9_fu_531_p2");
    sc_trace(mVcdFile, tmp2_cast_fu_543_p1, "tmp2_cast_fu_543_p1");
    sc_trace(mVcdFile, tmp3_cast_fu_546_p1, "tmp3_cast_fu_546_p1");
    sc_trace(mVcdFile, tmp1_fu_549_p2, "tmp1_fu_549_p2");
    sc_trace(mVcdFile, tmp6_cast_fu_559_p1, "tmp6_cast_fu_559_p1");
    sc_trace(mVcdFile, tmp8_cast_fu_562_p1, "tmp8_cast_fu_562_p1");
    sc_trace(mVcdFile, tmp5_fu_565_p2, "tmp5_fu_565_p2");
    sc_trace(mVcdFile, tmp1_cast_fu_555_p1, "tmp1_cast_fu_555_p1");
    sc_trace(mVcdFile, tmp5_cast_fu_571_p1, "tmp5_cast_fu_571_p1");
    sc_trace(mVcdFile, tmp_7_fu_575_p2, "tmp_7_fu_575_p2");
    sc_trace(mVcdFile, p_cast1_fu_581_p1, "p_cast1_fu_581_p1");
    sc_trace(mVcdFile, tmp11_fu_591_p3, "tmp11_fu_591_p3");
    sc_trace(mVcdFile, tmp12_fu_602_p3, "tmp12_fu_602_p3");
    sc_trace(mVcdFile, tmp11_cast_fu_598_p1, "tmp11_cast_fu_598_p1");
    sc_trace(mVcdFile, tmp12_cast_fu_608_p1, "tmp12_cast_fu_608_p1");
    sc_trace(mVcdFile, tmp10_fu_612_p2, "tmp10_fu_612_p2");
    sc_trace(mVcdFile, tmp13_fu_622_p4, "tmp13_fu_622_p4");
    sc_trace(mVcdFile, tmp10_cast_fu_618_p1, "tmp10_cast_fu_618_p1");
    sc_trace(mVcdFile, tmp14_cast_fu_630_p1, "tmp14_cast_fu_630_p1");
    sc_trace(mVcdFile, tmp_16_fu_634_p2, "tmp_16_fu_634_p2");
    sc_trace(mVcdFile, p_cast_fu_640_p1, "p_cast_fu_640_p1");
    sc_trace(mVcdFile, score_fu_259_p1, "score_fu_259_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

getRowScores::~getRowScores() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete elTetris2_fptruncbkb_U0;
    delete elTetris2_dadd_64cud_U1;
    delete elTetris2_dmul_64dEe_U2;
    delete elTetris2_ddiv_64eOg_U3;
    delete elTetris2_sitodp_fYi_U4;
}

void getRowScores::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void getRowScores::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_4024000000000000;
}

void getRowScores::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        elimCounter_reg_235 = elimCounter_2_s_fu_644_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        elimCounter_reg_235 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        rowTranCounter_reg_247 = rowTranCounter_2_s_fu_585_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        rowTranCounter_reg_247 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        row_reg_224 = row_1_reg_673.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        row_reg_224 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()))) {
        reg_280 = grp_fu_266_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        rowEliminated_load_reg_733 = rowEliminated_q0.read();
        tmp2_reg_742 = tmp2_fu_501_p2.read();
        tmp3_reg_747 = tmp3_fu_513_p2.read();
        tmp6_reg_752 = tmp6_fu_525_p2.read();
        tmp8_reg_757 = tmp8_fu_537_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        row_1_reg_673 = row_1_fu_352_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_10_reg_660 = tmp_10_fu_310_p2.read();
        tmp_13_reg_665 = tmp_13_fu_340_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_2_reg_782 = grp_fu_277_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read())) {
        tmp_4_reg_792 = grp_fu_272_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state53.read())) {
        tmp_5_reg_797 = grp_fu_262_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        tmp_reg_787 = grp_fu_277_p1.read();
    }
}

void getRowScores::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void getRowScores::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void getRowScores::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void getRowScores::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void getRowScores::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void getRowScores::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void getRowScores::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void getRowScores::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void getRowScores::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void getRowScores::thread_ap_CS_fsm_state47() {
    ap_CS_fsm_state47 = ap_CS_fsm.read()[46];
}

void getRowScores::thread_ap_CS_fsm_state48() {
    ap_CS_fsm_state48 = ap_CS_fsm.read()[47];
}

void getRowScores::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void getRowScores::thread_ap_CS_fsm_state53() {
    ap_CS_fsm_state53 = ap_CS_fsm.read()[52];
}

void getRowScores::thread_ap_CS_fsm_state54() {
    ap_CS_fsm_state54 = ap_CS_fsm.read()[53];
}

void getRowScores::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void getRowScores::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state54.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void getRowScores::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void getRowScores::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state54.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void getRowScores::thread_ap_return() {
    ap_return = score_fu_259_p1.read();
}

void getRowScores::thread_board_0_address0() {
    board_0_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_0_ce0 = ap_const_logic_1;
    } else {
        board_0_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_board_1_address0() {
    board_1_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_1_ce0 = ap_const_logic_1;
    } else {
        board_1_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_board_2_address0() {
    board_2_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_2_ce0 = ap_const_logic_1;
    } else {
        board_2_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_board_3_address0() {
    board_3_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_3_ce0 = ap_const_logic_1;
    } else {
        board_3_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_board_4_address0() {
    board_4_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_4_ce0 = ap_const_logic_1;
    } else {
        board_4_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_board_5_address0() {
    board_5_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_5_ce0 = ap_const_logic_1;
    } else {
        board_5_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_board_6_address0() {
    board_6_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_6_ce0 = ap_const_logic_1;
    } else {
        board_6_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_board_7_address0() {
    board_7_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_7_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_7_ce0 = ap_const_logic_1;
    } else {
        board_7_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_board_8_address0() {
    board_8_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_8_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_8_ce0 = ap_const_logic_1;
    } else {
        board_8_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_board_9_address0() {
    board_9_address0 =  (sc_lv<10>) (tmp_14_cast_fu_367_p1.read());
}

void getRowScores::thread_board_9_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        board_9_ce0 = ap_const_logic_1;
    } else {
        board_9_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_elimCounter_2_s_fu_644_p2() {
    elimCounter_2_s_fu_644_p2 = (!p_cast_fu_640_p1.read().is_01() || !elimCounter_reg_235.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_cast_fu_640_p1.read()) + sc_biguint<8>(elimCounter_reg_235.read()));
}

void getRowScores::thread_elimCounter_cast_fu_650_p1() {
    elimCounter_cast_fu_650_p1 = esl_zext<32,8>(elimCounter_reg_235.read());
}

void getRowScores::thread_exitcond1_fu_346_p2() {
    exitcond1_fu_346_p2 = (!row_reg_224.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_224.read() == ap_const_lv5_14);
}

void getRowScores::thread_grp_fu_266_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        grp_fu_266_p0 = tmp_reg_787.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_266_p0 = tmp_2_reg_782.read();
    } else {
        grp_fu_266_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void getRowScores::thread_grp_fu_266_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        grp_fu_266_p1 = ap_const_lv64_C009BE3C36D1935E;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_266_p1 = ap_const_lv64_400B8148A1086447;
    } else {
        grp_fu_266_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void getRowScores::thread_grp_fu_277_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_277_p0 = rowTranCounter_cast_fu_655_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_277_p0 = elimCounter_cast_fu_650_p1.read();
    } else {
        grp_fu_277_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void getRowScores::thread_p_cast1_fu_581_p1() {
    p_cast1_fu_581_p1 = esl_zext<8,4>(tmp_7_fu_575_p2.read());
}

void getRowScores::thread_p_cast_fu_640_p1() {
    p_cast_fu_640_p1 = esl_zext<8,4>(tmp_16_fu_634_p2.read());
}

void getRowScores::thread_p_shl1_cast_fu_336_p1() {
    p_shl1_cast_fu_336_p1 = esl_zext<11,8>(tmp_12_fu_328_p3.read());
}

void getRowScores::thread_p_shl2_cast_fu_294_p1() {
    p_shl2_cast_fu_294_p1 = esl_zext<11,10>(tmp_8_fu_286_p3.read());
}

void getRowScores::thread_p_shl3_cast_fu_306_p1() {
    p_shl3_cast_fu_306_p1 = esl_zext<11,8>(tmp_9_fu_298_p3.read());
}

void getRowScores::thread_p_shl_cast_fu_324_p1() {
    p_shl_cast_fu_324_p1 = esl_zext<11,10>(tmp_11_fu_316_p3.read());
}

void getRowScores::thread_rowEliminated_address0() {
    rowEliminated_address0 =  (sc_lv<10>) (tmp_15_cast_fu_386_p1.read());
}

void getRowScores::thread_rowEliminated_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        rowEliminated_ce0 = ap_const_logic_1;
    } else {
        rowEliminated_ce0 = ap_const_logic_0;
    }
}

void getRowScores::thread_rowTranCounter_2_s_fu_585_p2() {
    rowTranCounter_2_s_fu_585_p2 = (!p_cast1_fu_581_p1.read().is_01() || !rowTranCounter_reg_247.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_cast1_fu_581_p1.read()) + sc_biguint<8>(rowTranCounter_reg_247.read()));
}

void getRowScores::thread_rowTranCounter_cast_fu_655_p1() {
    rowTranCounter_cast_fu_655_p1 = esl_zext<32,8>(rowTranCounter_reg_247.read());
}

void getRowScores::thread_rowTran_1_cast_fu_407_p1() {
    rowTran_1_cast_fu_407_p1 = esl_zext<2,1>(tmp_6_1_fu_401_p2.read());
}

void getRowScores::thread_rowTran_2_cast_fu_417_p1() {
    rowTran_2_cast_fu_417_p1 = esl_zext<2,1>(tmp_6_2_fu_411_p2.read());
}

void getRowScores::thread_rowTran_3_cast_fu_427_p1() {
    rowTran_3_cast_fu_427_p1 = esl_zext<2,1>(tmp_6_3_fu_421_p2.read());
}

void getRowScores::thread_rowTran_4_cast_fu_437_p1() {
    rowTran_4_cast_fu_437_p1 = esl_zext<2,1>(tmp_6_4_fu_431_p2.read());
}

void getRowScores::thread_rowTran_5_cast_fu_447_p1() {
    rowTran_5_cast_fu_447_p1 = esl_zext<2,1>(tmp_6_5_fu_441_p2.read());
}

void getRowScores::thread_rowTran_6_cast_fu_457_p1() {
    rowTran_6_cast_fu_457_p1 = esl_zext<2,1>(tmp_6_6_fu_451_p2.read());
}

void getRowScores::thread_rowTran_7_cast_fu_467_p1() {
    rowTran_7_cast_fu_467_p1 = esl_zext<2,1>(tmp_6_7_fu_461_p2.read());
}

void getRowScores::thread_rowTran_8_cast_fu_477_p1() {
    rowTran_8_cast_fu_477_p1 = esl_zext<2,1>(tmp_6_8_fu_471_p2.read());
}

void getRowScores::thread_rowTran_9_cast_fu_487_p1() {
    rowTran_9_cast_fu_487_p1 = esl_zext<2,1>(tmp_6_9_fu_481_p2.read());
}

void getRowScores::thread_rowTran_cast_3_fu_497_p1() {
    rowTran_cast_3_fu_497_p1 = esl_zext<2,1>(tmp_6_s_fu_491_p2.read());
}

void getRowScores::thread_rowTran_cast_fu_397_p1() {
    rowTran_cast_fu_397_p1 = esl_zext<2,1>(tmp_s_fu_391_p2.read());
}

void getRowScores::thread_row_1_fu_352_p2() {
    row_1_fu_352_p2 = (!row_reg_224.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(row_reg_224.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void getRowScores::thread_row_cast_cast_fu_358_p1() {
    row_cast_cast_fu_358_p1 = esl_zext<11,5>(row_reg_224.read());
}

void getRowScores::thread_tmp10_cast_fu_618_p1() {
    tmp10_cast_fu_618_p1 = esl_zext<4,3>(tmp10_fu_612_p2.read());
}

void getRowScores::thread_tmp10_fu_612_p2() {
    tmp10_fu_612_p2 = (!tmp11_cast_fu_598_p1.read().is_01() || !tmp12_cast_fu_608_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp11_cast_fu_598_p1.read()) + sc_biguint<3>(tmp12_cast_fu_608_p1.read()));
}

void getRowScores::thread_tmp11_cast_fu_598_p1() {
    tmp11_cast_fu_598_p1 = esl_zext<3,2>(tmp11_fu_591_p3.read());
}

void getRowScores::thread_tmp11_fu_591_p3() {
    tmp11_fu_591_p3 = esl_concat<1,1>(rowEliminated_load_reg_733.read(), ap_const_lv1_0);
}

void getRowScores::thread_tmp12_cast_fu_608_p1() {
    tmp12_cast_fu_608_p1 = esl_zext<3,2>(tmp12_fu_602_p3.read());
}

void getRowScores::thread_tmp12_fu_602_p3() {
    tmp12_fu_602_p3 = esl_concat<1,1>(rowEliminated_load_reg_733.read(), rowEliminated_load_reg_733.read());
}

void getRowScores::thread_tmp13_fu_622_p4() {
    tmp13_fu_622_p4 = esl_concat<2,1>(esl_concat<1,1>(rowEliminated_load_reg_733.read(), rowEliminated_load_reg_733.read()), ap_const_lv1_0);
}

void getRowScores::thread_tmp14_cast_fu_630_p1() {
    tmp14_cast_fu_630_p1 = esl_zext<4,3>(tmp13_fu_622_p4.read());
}

void getRowScores::thread_tmp1_cast_fu_555_p1() {
    tmp1_cast_fu_555_p1 = esl_zext<4,3>(tmp1_fu_549_p2.read());
}

void getRowScores::thread_tmp1_fu_549_p2() {
    tmp1_fu_549_p2 = (!tmp2_cast_fu_543_p1.read().is_01() || !tmp3_cast_fu_546_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp2_cast_fu_543_p1.read()) + sc_biguint<3>(tmp3_cast_fu_546_p1.read()));
}

void getRowScores::thread_tmp2_cast_fu_543_p1() {
    tmp2_cast_fu_543_p1 = esl_zext<3,2>(tmp2_reg_742.read());
}

void getRowScores::thread_tmp2_fu_501_p2() {
    tmp2_fu_501_p2 = (!rowTran_1_cast_fu_407_p1.read().is_01() || !rowTran_cast_fu_397_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(rowTran_1_cast_fu_407_p1.read()) + sc_biguint<2>(rowTran_cast_fu_397_p1.read()));
}

void getRowScores::thread_tmp3_cast_fu_546_p1() {
    tmp3_cast_fu_546_p1 = esl_zext<3,2>(tmp3_reg_747.read());
}

void getRowScores::thread_tmp3_fu_513_p2() {
    tmp3_fu_513_p2 = (!rowTran_2_cast_fu_417_p1.read().is_01() || !tmp4_fu_507_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(rowTran_2_cast_fu_417_p1.read()) + sc_biguint<2>(tmp4_fu_507_p2.read()));
}

void getRowScores::thread_tmp4_fu_507_p2() {
    tmp4_fu_507_p2 = (!rowTran_4_cast_fu_437_p1.read().is_01() || !rowTran_3_cast_fu_427_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(rowTran_4_cast_fu_437_p1.read()) + sc_biguint<2>(rowTran_3_cast_fu_427_p1.read()));
}

void getRowScores::thread_tmp5_cast_fu_571_p1() {
    tmp5_cast_fu_571_p1 = esl_zext<4,3>(tmp5_fu_565_p2.read());
}

void getRowScores::thread_tmp5_fu_565_p2() {
    tmp5_fu_565_p2 = (!tmp6_cast_fu_559_p1.read().is_01() || !tmp8_cast_fu_562_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp6_cast_fu_559_p1.read()) + sc_biguint<3>(tmp8_cast_fu_562_p1.read()));
}

void getRowScores::thread_tmp6_cast_fu_559_p1() {
    tmp6_cast_fu_559_p1 = esl_zext<3,2>(tmp6_reg_752.read());
}

void getRowScores::thread_tmp6_fu_525_p2() {
    tmp6_fu_525_p2 = (!rowTran_5_cast_fu_447_p1.read().is_01() || !tmp7_fu_519_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(rowTran_5_cast_fu_447_p1.read()) + sc_biguint<2>(tmp7_fu_519_p2.read()));
}

void getRowScores::thread_tmp7_fu_519_p2() {
    tmp7_fu_519_p2 = (!rowTran_7_cast_fu_467_p1.read().is_01() || !rowTran_6_cast_fu_457_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(rowTran_7_cast_fu_467_p1.read()) + sc_biguint<2>(rowTran_6_cast_fu_457_p1.read()));
}

void getRowScores::thread_tmp8_cast_fu_562_p1() {
    tmp8_cast_fu_562_p1 = esl_zext<3,2>(tmp8_reg_757.read());
}

void getRowScores::thread_tmp8_fu_537_p2() {
    tmp8_fu_537_p2 = (!rowTran_8_cast_fu_477_p1.read().is_01() || !tmp9_fu_531_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(rowTran_8_cast_fu_477_p1.read()) + sc_biguint<2>(tmp9_fu_531_p2.read()));
}

void getRowScores::thread_tmp9_fu_531_p2() {
    tmp9_fu_531_p2 = (!rowTran_cast_3_fu_497_p1.read().is_01() || !rowTran_9_cast_fu_487_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(rowTran_cast_3_fu_497_p1.read()) + sc_biguint<2>(rowTran_9_cast_fu_487_p1.read()));
}

void getRowScores::thread_tmp_10_fu_310_p2() {
    tmp_10_fu_310_p2 = (!p_shl3_cast_fu_306_p1.read().is_01() || !p_shl2_cast_fu_294_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl3_cast_fu_306_p1.read()) + sc_biguint<11>(p_shl2_cast_fu_294_p1.read()));
}

void getRowScores::thread_tmp_11_fu_316_p3() {
    tmp_11_fu_316_p3 = esl_concat<6,4>(batch3.read(), ap_const_lv4_0);
}

void getRowScores::thread_tmp_12_fu_328_p3() {
    tmp_12_fu_328_p3 = esl_concat<6,2>(batch3.read(), ap_const_lv2_0);
}

void getRowScores::thread_tmp_13_fu_340_p2() {
    tmp_13_fu_340_p2 = (!p_shl1_cast_fu_336_p1.read().is_01() || !p_shl_cast_fu_324_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl1_cast_fu_336_p1.read()) + sc_biguint<11>(p_shl_cast_fu_324_p1.read()));
}

void getRowScores::thread_tmp_14_cast_fu_367_p1() {
    tmp_14_cast_fu_367_p1 = esl_zext<32,11>(tmp_14_fu_362_p2.read());
}

void getRowScores::thread_tmp_14_fu_362_p2() {
    tmp_14_fu_362_p2 = (!tmp_13_reg_665.read().is_01() || !row_cast_cast_fu_358_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_13_reg_665.read()) + sc_biguint<11>(row_cast_cast_fu_358_p1.read()));
}

void getRowScores::thread_tmp_15_cast_fu_386_p1() {
    tmp_15_cast_fu_386_p1 = esl_zext<32,11>(tmp_15_fu_381_p2.read());
}

void getRowScores::thread_tmp_15_fu_381_p2() {
    tmp_15_fu_381_p2 = (!tmp_10_reg_660.read().is_01() || !row_cast_cast_fu_358_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_10_reg_660.read()) + sc_biguint<11>(row_cast_cast_fu_358_p1.read()));
}

void getRowScores::thread_tmp_16_fu_634_p2() {
    tmp_16_fu_634_p2 = (!tmp10_cast_fu_618_p1.read().is_01() || !tmp14_cast_fu_630_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp10_cast_fu_618_p1.read()) + sc_biguint<4>(tmp14_cast_fu_630_p1.read()));
}

void getRowScores::thread_tmp_6_1_fu_401_p2() {
    tmp_6_1_fu_401_p2 = (board_0_q0.read() ^ board_1_q0.read());
}

void getRowScores::thread_tmp_6_2_fu_411_p2() {
    tmp_6_2_fu_411_p2 = (board_1_q0.read() ^ board_2_q0.read());
}

void getRowScores::thread_tmp_6_3_fu_421_p2() {
    tmp_6_3_fu_421_p2 = (board_2_q0.read() ^ board_3_q0.read());
}

void getRowScores::thread_tmp_6_4_fu_431_p2() {
    tmp_6_4_fu_431_p2 = (board_3_q0.read() ^ board_4_q0.read());
}

void getRowScores::thread_tmp_6_5_fu_441_p2() {
    tmp_6_5_fu_441_p2 = (board_4_q0.read() ^ board_5_q0.read());
}

void getRowScores::thread_tmp_6_6_fu_451_p2() {
    tmp_6_6_fu_451_p2 = (board_5_q0.read() ^ board_6_q0.read());
}

void getRowScores::thread_tmp_6_7_fu_461_p2() {
    tmp_6_7_fu_461_p2 = (board_6_q0.read() ^ board_7_q0.read());
}

void getRowScores::thread_tmp_6_8_fu_471_p2() {
    tmp_6_8_fu_471_p2 = (board_7_q0.read() ^ board_8_q0.read());
}

void getRowScores::thread_tmp_6_9_fu_481_p2() {
    tmp_6_9_fu_481_p2 = (board_8_q0.read() ^ board_9_q0.read());
}

void getRowScores::thread_tmp_6_s_fu_491_p2() {
    tmp_6_s_fu_491_p2 = (board_9_q0.read() ^ ap_const_lv1_1);
}

void getRowScores::thread_tmp_7_fu_575_p2() {
    tmp_7_fu_575_p2 = (!tmp1_cast_fu_555_p1.read().is_01() || !tmp5_cast_fu_571_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp1_cast_fu_555_p1.read()) + sc_biguint<4>(tmp5_cast_fu_571_p1.read()));
}

void getRowScores::thread_tmp_8_fu_286_p3() {
    tmp_8_fu_286_p3 = esl_concat<6,4>(batch31.read(), ap_const_lv4_0);
}

void getRowScores::thread_tmp_9_fu_298_p3() {
    tmp_9_fu_298_p3 = esl_concat<6,2>(batch31.read(), ap_const_lv2_0);
}

void getRowScores::thread_tmp_s_fu_391_p2() {
    tmp_s_fu_391_p2 = (board_0_q0.read() ^ ap_const_lv1_1);
}

void getRowScores::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_346_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_fsm_state44;
            break;
        case 8796093022208 : 
            ap_NS_fsm = ap_ST_fsm_state45;
            break;
        case 17592186044416 : 
            ap_NS_fsm = ap_ST_fsm_state46;
            break;
        case 35184372088832 : 
            ap_NS_fsm = ap_ST_fsm_state47;
            break;
        case 70368744177664 : 
            ap_NS_fsm = ap_ST_fsm_state48;
            break;
        case 140737488355328 : 
            ap_NS_fsm = ap_ST_fsm_state49;
            break;
        case 281474976710656 : 
            ap_NS_fsm = ap_ST_fsm_state50;
            break;
        case 562949953421312 : 
            ap_NS_fsm = ap_ST_fsm_state51;
            break;
        case 1125899906842624 : 
            ap_NS_fsm = ap_ST_fsm_state52;
            break;
        case 2251799813685248 : 
            ap_NS_fsm = ap_ST_fsm_state53;
            break;
        case 4503599627370496 : 
            ap_NS_fsm = ap_ST_fsm_state54;
            break;
        case 9007199254740992 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<54>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

