// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xeltetris2.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEltetris2_CfgInitialize(XEltetris2 *InstancePtr, XEltetris2_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEltetris2_Start(XEltetris2 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEltetris2_IsDone(XEltetris2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEltetris2_IsIdle(XEltetris2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEltetris2_IsReady(XEltetris2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEltetris2_EnableAutoRestart(XEltetris2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XEltetris2_DisableAutoRestart(XEltetris2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XEltetris2_Set_board_offset(XEltetris2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_BOARD_OFFSET_DATA, Data);
}

u32 XEltetris2_Get_board_offset(XEltetris2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_BOARD_OFFSET_DATA);
    return Data;
}

void XEltetris2_Set_landingHeight_offset(XEltetris2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_LANDINGHEIGHT_OFFSET_DATA, Data);
}

u32 XEltetris2_Get_landingHeight_offset(XEltetris2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_LANDINGHEIGHT_OFFSET_DATA);
    return Data;
}

void XEltetris2_Set_num_batches(XEltetris2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_NUM_BATCHES_DATA, Data);
}

u32 XEltetris2_Get_num_batches(XEltetris2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_NUM_BATCHES_DATA);
    return Data;
}

void XEltetris2_Set_scoreArrayOffset(XEltetris2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_SCOREARRAYOFFSET_DATA, Data);
}

u32 XEltetris2_Get_scoreArrayOffset(XEltetris2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_SCOREARRAYOFFSET_DATA);
    return Data;
}

void XEltetris2_InterruptGlobalEnable(XEltetris2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_GIE, 1);
}

void XEltetris2_InterruptGlobalDisable(XEltetris2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_GIE, 0);
}

void XEltetris2_InterruptEnable(XEltetris2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_IER);
    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XEltetris2_InterruptDisable(XEltetris2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_IER);
    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XEltetris2_InterruptClear(XEltetris2 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEltetris2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XEltetris2_InterruptGetEnabled(XEltetris2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_IER);
}

u32 XEltetris2_InterruptGetStatus(XEltetris2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEltetris2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XELTETRIS2_CTRL_BUS_ADDR_ISR);
}

